### ISSUE TITLE
follow .desktop entries symlinks

### ISSUE THREAD

**Issue by sanzoghenzo** [sanzoghenzo/wsl-tools#3]
**Describe the bug**
Symlinks in the desktop entries directory are not followed.

**To Reproduce**

1. Place a symlink in the WSL application directory
2. Check `WSLDistro.apps`
3. The app is not listed.

**Expected behavior**
The app should be listed.

**Comment by Pololot64** [comment]
I know you self assigned this but I did a quick implementation. I know the path implementation is slightly messy. #4
